/**
 * @description This is menu icon which got from backend.
 */
export default [
  'ant-design:bars-outlined',
  'ant-design:usergroup-add-outlined',
  'ant-design:user-outlined',
  'ant-design:menu-outlined',
  'ant-design:appstore-twotone',
  'ant-design:wallet-outlined',
  'ant-design:bulb-outlined',
  'ant-design:funnel-plot-outlined',
  'ant-design:appstore-outlined',
  'ant-design:table-outlined',
  'ant-design:align-center-outlined',
  'ant-design:form-outlined',
  'ant-design:appstore-add-outlined',
  'ant-design:down-circle-outlined',
  'ant-design:info-circle-outlined',
  'ant-design:link-outlined',
  'ant-design:pull-request-outlined',
  'ant-design:home-outlined',
  'ant-design:alert-outlined',
  'simple-icons:vite',
  'simple-icons:vuedotjs',
  'ant-design:dashboard-outlined',
  'mdi:library-shelves',
  'ant-design:barcode-outlined',
]
