export const defaultSuffix = ['@gmail.com', '@yahoo.com', '@sina.com']

export default [
  { iso2: 'US', suffix: ['@gmail.com', '@yahoo.com', '@hotmail.com', '@aol.com', '@msn.com', '@comcast.net', '@sbcglobal.net', '@icloud.com', '@att.net', '@verizon.net', '@outlook.com', '@me.com'] },
  { iso2: 'CN', suffix: ['@qq.com', '@126.com', '@163.com', '@sina.com', '@sohu.com', '@139.com', '@hotmail.com', '@gmail.com'] },
  { iso2: 'JP', suffix: ['@yahoo.co.jp', '@ezweb.ne.jp', '@docomo.ne.jp', '@i.softbank.jp'] },
  { iso2: 'KR', suffix: ['@naver.com', '@hanmail.net', '@daum.net', '@gmail.com', '@yahoo.co.kr', '@nate.com'] },
  { iso2: 'GB', suffix: ['@gmail.com', '@yahoo.co.uk', '@hotmail.co.uk', '@outlook.com', '@btinternet.com'] },
  { iso2: 'FR', suffix: ['@gmail.com', '@yahoo.fr', '@hotmail.fr', '@outlook.fr', '@laposte.net'] },
  { iso2: 'DE', suffix: ['@gmail.com', '@yahoo.de', '@hotmail.de', '@t-online.de', '@web.de'] },
  { iso2: 'IT', suffix: ['@gmail.com', '@yahoo.it', '@hotmail.it', '@libero.it'] },
  { iso2: 'RU', suffix: ['@mail.ru', '@yandex.ru', '@rambler.ru', '@list.ru'] },
  { iso2: 'BR', suffix: ['@gmail.com', '@yahoo.com.br', '@hotmail.com', '@outlook.com', '@bol.com.br'] },
  { iso2: 'MX', suffix: ['@gmail.com', '@yahoo.com.mx', '@hotmail.com', '@outlook.com', '@live.com.mx'] },
  { iso2: 'ES', suffix: ['@gmail.com', '@yahoo.es', '@hotmail.com', '@outlook.es'] },
  { iso2: 'AR', suffix: ['@gmail.com', '@yahoo.com.ar', '@hotmail.com', '@outlook.com'] },
  { iso2: 'CO', suffix: ['@gmail.com', '@yahoo.com.co', '@hotmail.com', '@outlook.com'] },
  { iso2: 'CL', suffix: ['@gmail.com', '@yahoo.cl', '@hotmail.com', '@outlook.com'] },
  { iso2: 'PE', suffix: ['@gmail.com', '@yahoo.com.pe', '@hotmail.com', '@outlook.com'] },
  { iso2: 'VE', suffix: ['@gmail.com', '@yahoo.com.ve', '@hotmail.com', '@outlook.com'] },
  { iso2: 'EC', suffix: ['@gmail.com', '@yahoo.com.ec', '@hotmail.com', '@outlook.com'] },
  { iso2: 'CR', suffix: ['@gmail.com', '@yahoo.com.cr', '@hotmail.com', '@outlook.com'] },
  { iso2: 'PA', suffix: ['@gmail.com', '@yahoo.com.pa', '@hotmail.com', '@outlook.com'] },
  { iso2: 'DO', suffix: ['@gmail.com', '@yahoo.com.do', '@hotmail.com', '@outlook.com'] },
  { iso2: 'GT', suffix: ['@gmail.com', '@yahoo.com', '@hotmail.com', '@outlook.com'] },
  { iso2: 'HN', suffix: ['@gmail.com', '@yahoo.com.hn', '@hotmail.com', '@outlook.com'] },
  { iso2: 'NI', suffix: ['@gmail.com', '@yahoo.com.ni', '@hotmail.com', '@outlook.com'] },
  { iso2: 'SV', suffix: ['@gmail.com', '@yahoo.com.sv', '@hotmail.com', '@outlook.com'] },
  { iso2: 'UY', suffix: ['@gmail.com', '@yahoo.com.uy', '@hotmail.com', '@outlook.com'] },
  { iso2: 'PY', suffix: ['@gmail.com', '@yahoo.com.py', '@hotmail.com', '@outlook.com'] },
  { iso2: 'BO', suffix: ['@gmail.com', '@yahoo.com.bo', '@hotmail.com', '@outlook.com'] },
  { iso2: 'CR', suffix: ['@gmail.com', '@yahoo.com.cr', '@hotmail.com', '@outlook.com'] },
  { iso2: 'SG', suffix: ['@gmail.com', '@yahoo.com.sg', '@hotmail.com', '@outlook.com'] },
  { iso2: 'AU', suffix: ['@gmail.com', '@yahoo.com.au', '@hotmail.com', '@outlook.com'] },
  { iso2: 'CA', suffix: ['@gmail.com', '@yahoo.ca', '@hotmail.com', '@outlook.com'] },
  { iso2: 'NZ', suffix: ['@gmail.com', '@yahoo.co.nz', '@hotmail.com', '@outlook.com'] },
  { iso2: 'ZA', suffix: ['@gmail.com', '@yahoo.co.za', '@hotmail.com', '@outlook.com'] },
]
