export const StoreKeys = {
  APP_ADAPTER: 'APP_ADAPTER',
  APP_DARK: 'APP_DARK',
  APP_KEY: 'APP_KEY',
  APP_LOCALE: 'APP_LOCALE',
  APP_LOCK: 'APP_LOCK',
  APP_MENU: 'APP_MENU',
  APP_SETTING: 'APP_SETTING',
  APP_TAB: 'APP_TAB',

  USER_PROFILE: 'USER_PROFILE',
  USER_AUTH: 'USER_AUTH',
  USER_PERMISSION: 'USER_PERMISSION',
} as const
