interface ImportMetaEnv {
  VITE_APP_TITLE: string

  VITE_PORT: number
  VITE_HOST: string

  VITE_API_TARGET: string
  VITE_API_PREFIX: string

  VITE_PROXY_PREFIX: string

  VITE_PUBLIC_PATH: string
  VITE_PERSIST_CRYPTO_KEY: string
  VITE_PERSIST_CRYPTO_IV: string

  VITE_REQUEST_CRYPTO_KEY: string
  VITE_REQUEST_CRYPTO_IV: string

  VITE_RESPONSE_CRYPTO_KEY: string
  VITE_RESPONSE_CRYPTO_IV: string

  VITE_AXIOS_TIMEOUT_SECOND: number
  VITE_AXIOS_CACHE_SECOND: number
  VITE_APP_PERSIST_SECOND: number
}
