export enum MutatationEnum {
  APP_TOGGLE_LANG = 'APP_TOGGLE_LANG',
  APP_TOGGLE_COLLAPSE = 'APP_TOGGLE_COLLAPSE',

  SET_TOKEN = 'SET_TOKEN',
  SET_USERINFO = 'SET_USERINFO',
  SET_MENU = 'SET_MENU',
  SET_KEEPALIVE = 'SET_KEEPALIVE',

  CREATE_TAB = 'CREATE_TAB',
  DELETE_TAB = 'DELETE_TAB',
  CLEAR_TAB = 'CLEAR_TAB',
}
