name: Create Release

on:
  push:
    tags:
      - 'v*' # 匹配所有以v开头的tag

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要获取完整历史记录才能访问标签

      - name: Verify release notes file
        run: |
          if [ ! -f "changelog-latest.md" ]; then
            echo "❌ 错误：未找到 changelog-latest.md 文件"
            exit 1
          fi

          # 验证发布说明内容
          if [ $(wc -l < changelog-latest.md) -lt 3 ]; then
            echo "⚠️ 警告：发布说明内容可能过短"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: changelog-latest.md
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up release notes
        run: |
          # 提交中移除 changelog-latest.md 文件
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git rm changelog-latest.md
          git commit -m "chore: remove changelog-latest.md after release"
          git push origin main
